stages:
  download:
    cmd: python src/data/download_data.py --url "https://datascientest-mlops.s3.eu-west-1.amazonaws.com/mlops_dvc_fr/raw.csv" --out data/raw/raw.csv
    deps:
      - src/data/download_data.py
    outs:
      - data/raw/raw.csv

  data_split:
    cmd: python src/data/data_split.py data/raw/raw.csv data/processed_data
    deps:
      - src/data/data_split.py
      - data/raw/raw.csv
    outs:
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
      - data/processed_data/y_train.csv
      - data/processed_data/y_test.csv

  normalize:
    cmd: python src/data/normalize.py data/processed_data data/processed_data
    deps:
      - src/data/normalize.py
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
    outs:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/X_test_scaled.csv
      - data/processed/scaler.pkl

  grid_search:
    cmd: python src/models/grid_search.py data/processed models/data/best_params.json
    deps:
      - src/models/grid_search.py
      - data/processed_data/X_train_scaled.csv
      - data/processed/y_train.csv
    outs:
      - models/data/best_params.json

  train:
    cmd: python src/models/train.py data/processed_data models/data/best_params.json models/model.pkl
    deps:
      - src/models/train.py
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
      - models/data/best_params.json
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/models/evaluate.py data/processed_data models/model.pkl metrics/scores.json data/predictions.csv
    deps:
      - src/models/evaluate.py
      - data/processed_data/X_test_scaled.csv
      - data/processed_data/y_test.csv
      - models/model.pkl
    metrics:
      - metrics/scores.json:
          cache: false
    outs:
      - data/predictions.csv
